--Author: Austin M. Allen

----------------------------------------------------------------
             -- WELCOME TO THE MY QUERY DEMO --
			  
   -- each query has it's own discription and insight --
 --  simply highlight and run the query you wanna see  --
----------------------------------------------------------------

-----------------------------{1}-----------------------------------

-- shows products based on how much revenue they generate
-- this year compared to the last two years

-- INSIGHT -- 
/*
The top selling product in 1998 was Cote de Blaye at $67,324.25 which showed a 21.3%
increase in revenue from $55,379.92 in 1997. However, out of the top five products this
year it was the only one to see an increase in revenue. The other four top revenue earners
all decreased. Thüringer Rostbratwurst went from $36183.82 to $33683.26 a 7% decrease.
Raclette Courdavault went from $39044.50 to $26345.00 a 32% decrease.Camembert Pierrot went
from $21301.00 to $17295.12 a 19% decrease. Tarte au sucre went from $22727.30 to $15992.92
a 30% decrease.
*/

with Product_Revenue as
(
select 
EXTRACT(year FROM order_date) as year,  
product_name as product,
round(sum((p.unit_price - (p.unit_price * discount)) * quantity)::numeric,2) as revenue

from products p
join order_details od on p.product_id = od.product_id
join orders o on od.order_id = o.order_id

group by year, product
),

 Lagging_Product_Revenue as
(
select year, product, revenue,
lag(revenue) over(partition by product order by year) as last_year,
lag(revenue,2) over(partition by product order by year) as two_years_ago
from Product_Revenue
)

select * from Lagging_Product_Revenue
where year = 1998
order by revenue desc;

------------------------------{2}----------------------------------

--shows the top 5 customers by order value this year (1998)

-- INSIGHT -- 
/*
The top 5 customers in 1998 generated $159,797.54 in revenue, the top 3 all generated at
least $36,000 in revenue with the last 2 generating $23,000 and $21,000 respectively. If we
compare the top 5 with the next 5 customers who generated a combine $80,552.46, that only
makes up 50.4% of what the top 5 customers generated. This shows a large disparity in
revenue generated by customers. Moreover, out of the 81 customers had in 1998 only 11
generated more than $10,000 in revenue.
*/

select 
c.customer_id,
company_name,
round(sum((od.unit_price - (od.unit_price * discount)) * quantity)::numeric,2) as revenue

from order_details od
join orders o on od.order_id = o.order_id
join customers c on o.customer_id = c.customer_id

where EXTRACT(year FROM order_date) = 1998
group by c.customer_id, company_name
order by revenue desc
limit 5;

--------------------------------{3}--------------------------------

--shows what countries have the highest average order value this year (1998)

-- INSIGHT -- 
/*
The highest average orders come from Ireland at $5,100.53 and Austria at $4090,97, with
a large drop off to the USA at $2,375.22 and other countries. This could indicate a need
for increased marketing in other countries and a look at why average orders values are so
high in Ireland and Austria.
*/

with order_revenue as
(
select 
o.order_id,
c.country,
sum((od.unit_price - (od.unit_price * od.discount)) * od.quantity) as order_value

from order_details od
join orders o on od.order_id = o.order_id
join customers c on o.customer_id = c.customer_id

where EXTRACT(year FROM order_date) = 1998
group by o.order_id, country
)

select 
country,
round(avg(order_value)::numeric, 2) as average_order_value

from order_revenue

group by country
order by average_order_value desc;

--------------------------------{4}--------------------------------

-- shows the top 3 customers that ordered the highest quantity of products each year

-- INSIGHT -- 
/*
There have been the same top 3 customers for all three years Save-a-lot Markets, Ernst Handel, and QUICK-Stop. Their order quantity
has increased from 2,097 products ordered in 1996 to 6,696 products ordered in 1997, with year three on track to increase as well
with 4,669 products ordered through just 5 months in 1998. This shows that not only are we getting repeat buisness 
but there is enough trust to increase the quantity they are ordering.     
*/

with customer_quantity as (
select 
EXTRACT(year FROM order_date) as year,
c.customer_id,
company_name,
sum(quantity) as number_of_products

from order_details od
join orders o on od.order_id = o.order_id
join customers c on o.customer_id = c.customer_id

group by year, c.customer_id, company_name
),

rank_customer as
(
select *,
rank()over(partition by year order by number_of_products desc) as customer_rank
from customer_quantity 
)

select * from rank_customer
where customer_rank in (1,2,3);

--------------------------------{5}--------------------------------

-- Shows the product that didn't sell the last 2 months and their price
-- (January and February 1998)

-- INSIGHT -- 
/*
There were 6 products that didn't sell over the last month. Out of the 6 products that didn't sell 2 of them 
have high price points with Queso Manchego La Pastora costing $38 and Vegie-spread costing $43.90. This doesn't
accounts for the other 4 items though as they all have average prices with Tofu at $23.25, Genen Shouyu at $13,
Valkoinen suklaa at $16.25, and Louisiana Hot Spiced Okra at $17. They could be higher end versions of similar
products though which could explain them not selling.
*/

with products_ordered_each_month as
(
select 
product_name as product,
EXTRACT(year FROM order_date) as year,  
EXTRACT(month FROM order_date) as month,
sum(quantity) as number_ordered

from products p
join order_details od on p.product_id = od.product_id
join orders o on od.order_id = o.order_id

group by year, month, product
),

products_ordered_last_month as
(
select * from products_ordered_each_month
where year = 1998 and month in (1,2)
)

select product_name, unit_price from products
where not exists 
	(select 1 
	from products_ordered_last_month as plm 
	where plm.product = product_name);
	
--------------------------------{6}--------------------------------

-- shows internal shipping performance (date ordered to date shipped)
-- and categorizes each orders performance status for the last 2 months
-- (January and February 1998)

-- INSIGHT -- 
/*
There were 279 internal shipments in the last 2 months with 43 Critically Delayed, 90
Delayed, 109 Good, and 37 Excellent. This shows that 47.8% of internal shipments had some
kind of delay. This could damage customer trust which seems to be very important for this company
based on past insights so this issue should be looked into immediately. 
*/

with shipping_dates as
(
select 
c.customer_id as company_id,
company_name as company,
product_name as product,
order_date, 
shipped_date,
EXTRACT(year FROM shipped_date) as year_shipped,  
EXTRACT(month FROM shipped_date) as month_shipped

from products p
join order_details od on p.product_id = od.product_id
join orders o on od.order_id = o.order_id
join customers c on o.customer_id = c.customer_id 

),

last_2_month as
(
select * from shipping_dates
where year_shipped = 1998 and month_shipped in (1,2)
)

select Company, Product, month_shipped as month, 
case
	When shipped_date is null then 'Not Shipped Yet'
	When (shipped_date - order_date) <= 3 then 'Excellent'
	When (shipped_date - order_date) between 4 and 7 then 'Good'
	When (shipped_date - order_date) between 8 and 14 then 'Delayed'
	When (shipped_date - order_date) > 14 then 'Critically Delayed'
end as internal_shipping_performance

from last_2_month
order by month_shipped asc;

